import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar";

const inter = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight:["100","200","300","400","500"], 
  variable: '--font-jetbrainsMono'
});

export const metadata: Metadata = {
  title: "sampath.info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
        {children}
      </body>
    </html>
  );
}
